# Generated by Django 5.0.3 on 2024-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="data_nascimento",
            field=models.DateField(),
        ),
    ]
